### ISSUE TITLE
Improvement on Med home-screenpage

### ISSUE THREAD

**Issue by Show-M** [weaveio/forum#101]
Create following home-screen of Med page. 
This must be done in order to let patients add meds depending on its use of occasion
One for Regular med, 
Another for Asthma-attack med,

Both will use same set of data.

お薬手帳
-常用薬-
[ADD]

...
-発作薬-
[ADD]

...
Default screen
<img width="1429" alt="スクリーンショット 2021-04-09 21 23 06" src="https://user-images.githubusercontent.com/61481039/114179709-49506f00-997a-11eb-973d-1a3c49485cad.png">

**Comment by Show-M** [comment]
ref #73

**Comment by sarikabhimre18** [comment]
@Show-M Please check it in latest bulid

**Comment by Show-M** [comment]
When the search gives long list, it has overlap with  "緊急薬" section
<img width="1434" alt="スクリーンショット 2021-04-12 13 54 07" src="https://user-images.githubusercontent.com/61481039/114342374-b5a7ba00-9b96-11eb-82b4-5315bfc8d3d7.png">

**Comment by Show-M** [comment]
According to Sarika, 
This is fixed on her latest built, which i do not have yet.  So, we ignore and i am closing it.
