### ISSUE TITLE
Shortcut:web is not working on Asthma org

### ISSUE THREAD

**Issue by Show-M** [weaveio/forum#105]
<img width="1439" alt="スクリーンショット 2021-04-13 12 03 03" src="https://user-images.githubusercontent.com/61481039/114491164-185d8c00-9c51-11eb-910b-a4fd4a2a3d64.png">
<br>
![1](https://user-images.githubusercontent.com/61481039/114491182-1f849a00-9c51-11eb-9b8a-637a1753c1f8.gif)

**Comment by rgagne** [comment]
They are not set to show to anyone:

![image](https://user-images.githubusercontent.com/428897/114495407-f6680780-9c58-11eb-86ef-498862380c23.png)

**Comment by Show-M** [comment]
I didnt remember that i made any security setting changes...
