### ISSUE TITLE
Displayed date on medicine-note main screen & actual dispatch data do not match

### ISSUE THREAD

**Issue by Show-M** [weaveio/forum#112]
This could be caused by some system update...because non of us haven't touched it since last time.
So, if you are not sure what to look, please check with Rob.
Please work on it asap.
<img width="1056" alt="スクリーンショット 2021-04-25 22 26 39" src="https://user-images.githubusercontent.com/61481039/115995272-98063600-a615-11eb-8e31-f2b40e8ba045.png">
<img width="1100" alt="スクリーンショット 2021-04-25 22 26 50" src="https://user-images.githubusercontent.com/61481039/115995274-99376300-a615-11eb-8975-1cbdd0ca5277.png">

**Comment by rgagne** [comment]
Not a bug; just bad format in the configuration.
