### ISSUE TITLE
Want to capture as toggle-button and display as text with title mapping from value..

### ISSUE THREAD

**Issue by Show-M** [weaveio/forum#121]
Issue is that if i change from dspatch-wrapper to toggle-button, it does not work anymore..
```
{
  "type": "string",
  "$capture": {
    "as": "dispatch-wrapper",
    "query": "current user, given tracker [asthma-attack-medicine]",
    "onDispatch": [
      {
        "pick": "values.number_a_day",
        "apply": "sum(ls)",
        "save": "goal"
      }
    ],
    "onGroupChange": [
      {
        "pick": "{size(values.self)}",
        "apply": "sum(ls)",
        "save": "status"
      }
    ],
    "form": {
      "as": "toggle-button",
      "mode": "list",
      "width": "full",
      "styles": {
        "title": {
          "fontSize": "1rem"
        }
      },
      "classes": {
        "root": "mt-2"
      }
    },
    "mapping": [
      {
        "from": "values",
        "to": "title",
        "template": "{values.name}"
      },
      {
        "from": "id",
        "to": "$api"
      }
    ]
  },
  "$display": {
    "as": "text",
    "rule": {
      "setting": "always"
    }
  },
  "title": "緊急時薬",
  "$data": {
    "source": [
      {
        "display": "使用した",
        "value": "使用した",
        "tableData": {
          "id": 0
        }
      },
      {
        "display": "使用していない",
        "value": "使用していない",
        "tableData": {
          "id": 1
        }
      }
    ]
  }
}
```

**Comment by Show-M** [comment]
![IMG_0293](https://user-images.githubusercontent.com/61481039/119161185-fba84580-ba93-11eb-8840-023641e46ff5.PNG)
![IMG_0294](https://user-images.githubusercontent.com/61481039/119161191-fcd97280-ba93-11eb-9b87-c8a7d9f82e99.PNG)

**Comment by rgagne** [comment]
mode === "list" means that it will allow more than one thing to be selected

**Comment by rgagne** [comment]
Relevant docs: https://docs.fluxweave.com/Configuration/Trackers/Capture/ToggleButton/

**Comment by Show-M** [comment]
I managed to fix the mode...
But what to display on dispatch is not configured yet.
![IMG_0294](https://user-images.githubusercontent.com/61481039/119161191-fcd97280-ba93-11eb-9b87-c8a7d9f82e99.PNG)

**Comment by Show-M** [comment]
**this is affecting Top tracker dispatch too.**

**Comment by rgagne** [comment]
Here's the data in the dispatch

```
{
  "asthmaattackSeverity": "大発作",
  "asthmaattackSeizures": "その他",
  "1effa1c9-dc1e-4e62-8f71-49dcd19eecef": "使用していない",
  "c3af87b7-3314-4732-9f10-c61bbe169f94": "使用していない"
}
```

Sounds like additional data is also needed to be stored.

**Comment by rgagne** [comment]
latest version addresses this

**Comment by Show-M** [comment]
![IMG_0329](https://user-images.githubusercontent.com/61481039/120617615-4020e180-c495-11eb-9299-1546290c9a85.PNG)
![IMG_0330](https://user-images.githubusercontent.com/61481039/120617632-43b46880-c495-11eb-8566-11c044c94faa.PNG)
