### ISSUE TITLE
How to connect unique ID provided by Dr and External ID in the system

### ISSUE THREAD

**Issue by Show-M** [weaveio/forum#133]
To be considered:
- Unique ID provided by Dr should be unique in the system
- Dr should be able to find patients in the system using the ID

Do we ask users to type in after entering Asthma org? 
Or 
As they type in once as user name when they join Chant org, Do we let the system to add their unique ID to External ID when users enter Join code for asthma ?

**Comment by rgagne** [comment]
Couple notes:

1. Unique id provided by the doctor CANNOT be unique in the system. That is not something we can support in a multi-tenant system. Org A and Org B may have an overlapping convention (user 1000, 1001, 1002, etc) which would not be supportable. 
2. For this initial launch users should just put their system id as their Display Name.

We'll make a way to ask for the "external id" for each org that is easy to use and defaults to Display Name entered. We can then update existing users as needed.
