### ISSUE TITLE
Can I create a body map, which patients can choose and tap on?

### ISSUE THREAD

**Issue by Show-M** [weaveio/forum#38]
There was a request to show the area where the medicine was applied or the itchy part was on patient's body. 
It is a rough idea, so
In the figure on the left, face, shoulders, chest, belly, upper arms, back of elbows, arms, hands, thighs, thighs, legs etc...
I want to make something that patients select the part of body.
Since the area calculation will be done by us, I would like to have you make something like the figure and create something that you can select by tapping.

Body map
<img width="430" alt="スクリーンショット 2021-01-24 11 22 04" src="https://user-images.githubusercontent.com/61481039/105619496-6d4deb00-5e36-11eb-8886-adb0b227007f.png">

Patients choose & tap
<img width="577" alt="スクリーンショット 2021-01-24 11 22 12" src="https://user-images.githubusercontent.com/61481039/105619504-7b037080-5e36-11eb-91a2-f1cc371b3e2c.png">

**Comment by Show-M** [comment]
@hiroki-330 
こちら必須でないのでしたら、クローズして宜しいでしょうか？

**Comment by shunyaogawa** [comment]
Since it is my essential function, I will issue a new function request ticket.
Sorry for the late reply.

私の必須機能なので、私から新機能リクエストチケットを発行させていただきます。
返信が遅れてしまい申し訳ありません。
