### ISSUE TITLE
Speech to text

### ISSUE THREAD

**Issue by hiroki-330** [weaveio/forum#43]
![S__9797646](https://user-images.githubusercontent.com/78060608/106822848-35ab3280-66c3-11eb-8f49-43d0aa2399c3.jpg)

I want to input voice with trackers.
Please tell me how to use voice input.

**Comment by rgagne** [comment]
If you create a block input text metric then you'll have as the normal part of the soft keyboard (the user clicks the microphone icon). However we don't have a "voice input" metric.

To understand the functionality the desire is:
1. User clicks some button
2. Immediately the microphone starts recording the users speech
3. Speech is converted to text by the text-to-speech module and stored as a data attribute

Is that accurate?

**Comment by hiroki-330** [comment]
that is accurate.
よろしくお願いします。
