### ISSUE TITLE
権限について

### ISSUE THREAD

**Issue by jbd-ooji** [weaveio/forum#46]
@Show-M 
JBDから新たにプロジェクトに参画することになりました大治　健人と申します。
よろしくお願い申し上げます。

お忙しいところ恐縮ですが、現在私のアカウントには、githubの編集権限がない状態となっております。
権限の付与、プロジェクトへの参加方法についてご教示いただけますと幸いです。

**Comment by jbd-ooji** [comment]
同じく、TestFlightにも参加できていない状態です。
こちらにつきましても、ご対応をお願い申し上げます。

**Comment by Show-M** [comment]
@jbd-ooji 
よろしくお願いいたします。
まずはじめにですが、メールアドレスをいただけますか？(それがないと権限付与ができません)
ただし、私のメール宛に直接いただければと思います。
Testflightは、Weaveでは既に使用しておりません。iOSまたはAndroidマーケットで「fluxweave」と検索すれば出てきますので、ダウンロードし登録してみて下さい。
