### ISSUE TITLE
Drop down looks bad when the title is over 1 sentence

### ISSUE THREAD

**Issue by Show-M** [weaveio/forum#47]
As Japanese sentence tends to be long, it is useful to use drop down on tracker.
But it looks not really good...
Question 2 and 3, both are dropdown.

![IMG_0202](https://user-images.githubusercontent.com/61481039/107601807-08cec080-6c6b-11eb-8e4f-95b2970d14f1.PNG)
<img width="1404" alt="スクリーンショット 2021-02-11 13 13 11" src="https://user-images.githubusercontent.com/61481039/107601777-f5235a00-6c6a-11eb-97e3-ee955f5d8d92.png">

**Comment by rgagne** [comment]
Not sure a dropdown is the best option here; probably better to use a wizard view (one page per question) with radio buttons

**Comment by Show-M** [comment]
ok.
