### ISSUE TITLE
time range

### ISSUE THREAD

**Issue by hiroki-330** [weaveio/forum#48]
![Fluxweave および他 4 ページ - 職場 - Microsoft​ Edge 2021_02_12 13_49_12](https://user-images.githubusercontent.com/78060608/107731496-7c3f0380-6d39-11eb-88f7-61337ff2f10e.png)
The above is normal in the Web version, but the timerange is strange in the mobile version. 
![S__10305539](https://user-images.githubusercontent.com/78060608/107731509-84973e80-6d39-11eb-86a5-077d929ad11f.jpg)

上がWeb版で異常ないのですが、したのmobile版ではtimerangeおかしくなってしまいます。
よろしくお願いします。

**Comment by Show-M** [comment]
@hiroki-330 

以下に変更してみました。今は両方とも動作するはずです。
`
{
  "type": "string",
  "title": "じっさい",
  "$capture": {
    "as": "clock-range",
    "enabled": true,
    "confirm": false
  },
  "$display": {
    "as": "clock-range"
  },
  "default": "now +30"
}
`

Ruleを間違って消してしまったので、そちらの再設定だけお願いします・・・。

**Comment by hiroki-330** [comment]
ありがとうございます
