### ISSUE TITLE
Allowance of data entry only once a month for a tracker

### ISSUE THREAD

**Issue by Show-M** [weaveio/forum#49]
I need to allow users to make entries **only once a month** for a tracker, CACT.
<img width="1425" alt="スクリーンショット 2021-02-13 13 42 31" src="https://user-images.githubusercontent.com/61481039/107841813-993f0980-6e01-11eb-8e5d-df02df40d5e1.png">

**Comment by rgagne** [comment]
This wouldn't be a tracker feature. It is a user flow, e.g. show the user that they have or have not entered the tracker.

**Comment by Show-M** [comment]
more details:

1. User create an entry for a tracker
2. within the same month, no more entry to a tracker is allowed.

What users can do is either 
- deleting the existing entry and create new one 
   OR 
- modifying the existing entry

**Comment by rgagne** [comment]
This would not be a tracker feature but user flow.

How will the user see / enter the tracker? A dashboard that is keyed to month?

**Comment by Show-M** [comment]
from calendar....
<img width="847" alt="スクリーンショット 2021-02-16 16 37 08" src="https://user-images.githubusercontent.com/61481039/108032111-4d949600-7075-11eb-932f-6ae48db67faa.png">

On as-is, users can check added-entries on tracker, itself. caz each tracker let users "add & see" the data.
*video is a screen corresponding to "top" screen on to-be.
![1](https://user-images.githubusercontent.com/61481039/108032663-2b4f4800-7076-11eb-920e-61479ff20c1e.gif)

We can make dashbaord or add on profile or smth...any idea? considering this popup(dont enter more than once a month)

**Comment by rgagne** [comment]
Addressed with new dashboard; see https://github.com/weaveio/forum/issues/56
