### ISSUE TITLE
Did I set something wrong? t Navigation-->Target:link does not work

### ISSUE THREAD

**Issue by Show-M** [weaveio/forum#50]
This is not a function needed for the app but i wanted to give a try...
<img width="1378" alt="スクリーンショット 2021-02-13 14 33 54" src="https://user-images.githubusercontent.com/61481039/107842722-a90e1c00-6e08-11eb-8bd9-33c3d04ff44d.png">

**Comment by rgagne** [comment]
It works from the side menu but not from the button bar.

```
{
  "url": "itms-apps://itunes.apple.com/app/784332002",
  "system": true
}
```
The correct URL is (though apps.apple.com also works.. just requires a redirect)
