### ISSUE TITLE
Define what to display on target: calendar 

### ISSUE THREAD

**Issue by Show-M** [weaveio/forum#51]
Currently when i add day format, it gets applied to all the trackers
`
"dayFormat": [
      ":color",
      ":icon",
      ":template"
    ]
`
But I want to display as below(applying different format to each tracker).
<img width="770" alt="スクリーンショット 2021-02-15 19 12 06" src="https://user-images.githubusercontent.com/61481039/107933402-0b5e4c80-6fc2-11eb-997e-dd49b087cc88.png">
<img width="1126" alt="スクリーンショット 2021-02-15 19 11 38" src="https://user-images.githubusercontent.com/61481039/107933414-0dc0a680-6fc2-11eb-9900-005f218fded5.png">
<br>
<br>
<br> 

<img width="1432" alt="スクリーンショット 2021-02-15 19 09 07" src="https://user-images.githubusercontent.com/61481039/107932937-778c8080-6fc1-11eb-96e4-66092927af06.png">

**Comment by Show-M** [comment]
Also, perhaps size or space adjustments are important for phone-app. 
It is cutting off. 
![IMG_7E20A075F6FA-1](https://user-images.githubusercontent.com/61481039/110460071-14e65a80-8111-11eb-817c-80cdcc9378c4.jpeg)

**Comment by rgagne** [comment]
For mobile: this is all by design.. check out any of the phone based calendar apps. They do the exact same thing. I think the mobile side is already fully configurable.

**Comment by Show-M** [comment]
ok, Then....will we do that? if not, i will inform so, that it is by default.

**Comment by rgagne** [comment]
Added

**Comment by Show-M** [comment]
```
"options": {
    "query": "current user",
    "dayFormat": [
      ":icon",
      ":template"
    ]
  },
```



 ```
   "trackerDayFormat": {
      "cact": [
        ":icon",
        ":template"
      ],
      "Examination-Result": [
        ":template"
      ],
      "top": [
        ":template"
      ],
      "asthmaattack": [
        ":template"
      ]
    }
```
