### ISSUE TITLE
When I enter the time, the app crashes.

### ISSUE THREAD

**Issue by hiroki-330** [weaveio/forum#53]
I thought it would take some time to reflect, so I left it for a day.
However, the app has crashed as shown in the video below. 
location: 復職支援のtracker  test24 
反映に時間がかかってると思い一日置いたが、下の動画のようにアプリが落ちてしまった。

https://user-images.githubusercontent.com/78060608/108008671-37221680-7044-11eb-880a-0a1ea317f130.MP4

**Comment by hiroki-330** [comment]
場所は　復職支援のtracker  test24 です

**Comment by Show-M** [comment]
@rgagne 
Can you have a look why the app crushes?

Reproduction is above.

Location of that tracker is below.
<img width="1432" alt="スクリーンショット 2021-02-19 15 45 17" src="https://user-images.githubusercontent.com/61481039/108468110-96448d00-72c9-11eb-95c9-1677eadaa79b.png">

**Comment by Show-M** [comment]
@rgagne 
<img width="1432" alt="スクリーンショット 2021-02-19 15 45 17" src="https://user-images.githubusercontent.com/61481039/108468110-96448d00-72c9-11eb-95c9-1677eadaa79b.png">

When There is no rule set, clock range works fine. 
But if we add rule below, it will crush  as the reproduction video shows. 
```
"rule": {
      "setting": "rule",
      "text": "values.activity == 'breakfast' or values.activity == 'lunch' or values.activity == 'dinner' or values.activity == 'snack' or values.activity == 'movement' or values.activity == 'hobby' or values.activity == 'out' or values.activity == 'other' or values.activity == 'sleep' or values.activity == 'bath' or values.activity == 'med'"
    }
```


Can you tell us why it is happening?

**Comment by hiroki-330** [comment]
Thank you.
I don't know why it's happeninng.
I want to do it without rules.

**Comment by Show-M** [comment]
Ruleを適用しなくていいのでしたら、現在既に修正済みです。
Rule付加による誤作動の原因は、現在開発チームに確認中ですので、しばしお待ち下さい。
