### ISSUE TITLE
Alarm function

### ISSUE THREAD

**Issue by Show-M** [weaveio/forum#54]
Let me know your thought.

Requirement:

1. Each patients will manage all  and set their own alarms 
2. Everyday at the set time, alarms should be triggered
3. set time should be able to be adjust accordingly
4. For added alarms, in order to cancel if there is ON/OFF function, that would be great(preferred than deleting)
5. Alarm will create popup(notification) and let users know.(it is same as notification  we get on current weave app)
6. Max number of alarms to set is 3(morning/afternoon/evening)

** It appeared that alarm function is an individual function. Meaning, it has nothing connected to "added medicine" etc.

<img width="893" alt="スクリーンショット 2021-02-26 17 03 21" src="https://user-images.githubusercontent.com/61481039/109272816-bdb0d200-7854-11eb-8b50-9731c56246b3.png">

**Comment by rgagne** [comment]
List
<img src="https://user-images.githubusercontent.com/428897/109748170-bd7d5180-7c1b-11eb-82bf-11fc3353fd78.png" width="200"/>

Add
<img src="https://user-images.githubusercontent.com/428897/109748168-bce4bb00-7c1b-11eb-816d-952a73682336.png" width="200"/>

Edit
<img src="https://user-images.githubusercontent.com/428897/109748167-bbb38e00-7c1b-11eb-9178-c0bb2da1fdfc.png" width="200"/>

You can add / remove as many as desired.

**Comment by Show-M** [comment]
It does not ring....my version is 3.0.2453

**Comment by rgagne** [comment]
Don't re-use tickets...

https://github.com/weaveio/forum/issues/81
