### ISSUE TITLE
Deleting shortcut(+) on specific page

### ISSUE THREAD

**Issue by shunyaogawa** [weaveio/forum#55]
I want to delete the shortcut mark on this calendar screen. What should I do?
![karenda-2](https://user-images.githubusercontent.com/78076746/108472423-11a93d00-72d0-11eb-84fb-e2d90caab17b.png)

**Comment by Show-M** [comment]
@rgagne 
Not sure how to do this...can you help?

**Comment by rgagne** [comment]
add `calendar` to the blacklist

![image](https://user-images.githubusercontent.com/428897/109152407-ca7aea80-77ae-11eb-8d74-06c7efa6841b.png)

**Comment by Show-M** [comment]
This might be used also on Asthma app. We will see after talk with Dr.

**Comment by Show-M** [comment]
@rgagne 
Isn't this how you delete the SHORTCUT? It seems to be working.
<img width="1160" alt="スクリーンショット 2021-03-13 13 25 56" src="https://user-images.githubusercontent.com/61481039/111018985-aac70180-83ff-11eb-8b16-98dd04b3c7be.png">

**Comment by rgagne** [comment]
That will delete it for every screen. if that's the goal then yes. if you want to remove it for a particular screen then we need to add a function.

**Comment by rgagne** [comment]
noSpeedDial will remove it for a specific screen; goes in navigation options

https://docs.fluxweave.com/Configuration/Navigation/Options/

```
"options": {
  "noSpeedDial": ["calendar"]
}
```
