### ISSUE TITLE
Asthma App - Frequency of Each Item

### ISSUE THREAD

**Issue by Show-M** [weaveio/forum#56]
#### Users should enter each day
- Top

#### User should enter each __ whatever the period
- CACT(Once a month)

#### User should enter only when there is some problem
- Asthma Attack(Only when Asthma attack occurs)
- Examination Result(Whenever users take examination)

<img width="278" alt="スクリーンショット 2021-02-22 18 56 27" src="https://user-images.githubusercontent.com/61481039/108692818-723eb100-7540-11eb-9d04-66adfa9cc26b.png">

**Comment by rgagne** [comment]
See build 3.0.2445 - upper right menu; Dashboard

New functionality available

**Comment by rgagne** [comment]
<img src="https://user-images.githubusercontent.com/428897/109410289-c0d6ca00-79dc-11eb-8ef8-c73d565ba749.png" data-canonical-src="https://user-images.githubusercontent.com/428897/109410289-c0d6ca00-79dc-11eb-8ef8-c73d565ba749.png" width="350" />
