### ISSUE TITLE
stream character

### ISSUE THREAD

**Issue by shunyaogawa** [weaveio/forum#57]
Org is a "お肌手帳" and tracker is a "自由記入欄".

I want to be able to display the character string entered from the tracker in "stream".
I was able to display the numbers with {values. ~~}, but the character string was not displayed even if I did the same.
Could you tell me how?
![stream](https://user-images.githubusercontent.com/78076746/108809329-f437e400-75eb-11eb-8a05-91a1c316c625.png)

**Comment by Show-M** [comment]
@shunyaogawa 
こちら、どのOrgのどの場所(トラッカー?)を指しているのでしょうか？
また、以下の情報は毎回選択するようにお願い致します。。
Projectに入っていないと、新規チケットの確認が遅れてしまうことがありますので・・・。よろしくお願い致します。
<img width="1279" alt="スクリーンショット 2021-02-25 10 42 53" src="https://user-images.githubusercontent.com/61481039/109090558-7fcd8400-7756-11eb-8594-b779497df2b5.png">

**Comment by shunyaogawa** [comment]
Thank you for your reply.
I'm sorry about Project. I will be careful from the next time.

Org is a "お肌手帳" and tracker is a "自由記入欄".

よろしくお願いいたします。

**Comment by Show-M** [comment]
こういう事でよろしいでしょうか？
そうでしたら、単純にValueの置き場所が間違っていたようです。

<img width="1076" alt="スクリーンショット 2021-02-25 18 25 29" src="https://user-images.githubusercontent.com/61481039/109132267-fbe7bc00-7796-11eb-976c-d29f61b15cb6.png">
<img width="584" alt="スクリーンショット 2021-02-25 18 24 36" src="https://user-images.githubusercontent.com/61481039/109132061-c511a600-7796-11eb-91c0-49b2e8f5c6a8.png">

**Comment by shunyaogawa** [comment]
I'm sorry for the rudimentary mistake.
Thank you for resolving it.
