### ISSUE TITLE
CACT should be able to have only one-entry per month

### ISSUE THREAD

**Issue by Show-M** [weaveio/forum#59]
I dont know if it is possible to turn off CACT once users make an entry in a month.

If not, at least dashboard should carry the entry to next day. So that, users know that they already made an entry for the month.
![IMG_0220](https://user-images.githubusercontent.com/61481039/109471197-c521e680-7ab3-11eb-919b-10c20afbdb3c.PNG)
![IMG_0221](https://user-images.githubusercontent.com/61481039/109471199-c6531380-7ab3-11eb-864c-aa2c91ef2c1f.PNG)

**Comment by Show-M** [comment]
This is a continuous RQ from #49

**Comment by rgagne** [comment]
updated the configuration; it's based on the filter
