### ISSUE TITLE
when you set condition on compute, the calculation is not processed

### ISSUE THREAD

**Issue by Show-M** [weaveio/forum#62]
When there is such a case below, compete does not work somehow...
Without condition, it just works fine.

```
{
  "type": "string",
  "$capture": {
    "as": "compute",
    "expression": "(values.CACTQ1 + values.CACTQ2 + values.CACTQ3 + values.CACTQ4 + values.CACTQ5)"
  },
  "$display": {
    "as": "header",
    "rule": {
      "setting": "rule",
      "text": "values.cactage is '12歳以上'"
    }
  },
  "title": "CACT合計得点(12歳以上)"
}
```

<img width="1430" alt="スクリーンショット 2021-03-02 11 57 30" src="https://user-images.githubusercontent.com/61481039/109590073-b0466100-7b4e-11eb-8653-47e9d94562b2.png">

**Comment by Show-M** [comment]
To compare data for "4-11" and "Over 12"
`given dispatch[0645b37f-291a-442f-b723-a2ae4f70d3fc, 9360be55-04cb-440c-b94d-637dd931e2dd]`

**Comment by rgagne** [comment]
It seems to be working; I applied the rule and it hides when it should hide but shows it appropriately. Can you post the screen shots for what should be?

Rule hiding the control
![Screenshot from 2021-03-03 10-11-48](https://user-images.githubusercontent.com/428897/109737193-f8c25500-7c08-11eb-9211-dd468056d67b.png)

Rule showing the control; compute processed
![Screenshot from 2021-03-03 10-11-35](https://user-images.githubusercontent.com/428897/109737194-f95aeb80-7c08-11eb-8523-0beb9d6fd2a3.png)

**Comment by rgagne** [comment]
Did you actually want `values.cactage not '12歳以上'`

In trackers the value is HIDDEN (or disabled) when the rule is FALSE. That can sometimes be counter intuitive depending on the goal.

I updated the rules to be "not" and I think that's what you were looking for.

**Comment by Show-M** [comment]
that makes sense...counter intuitive :v
