### ISSUE TITLE
Text change for Alarm

### ISSUE THREAD

**Issue by Show-M** [weaveio/forum#64]
Text there to be changed to following...

設定時刻

It means "time that was set". if you can add some space between "設定時刻" and "07:51 PM", that is great.

![IMG_0223](https://user-images.githubusercontent.com/61481039/109795285-166bda80-7c5a-11eb-869a-5485747a2793.PNG)

**Comment by rgagne** [comment]
actually a bug with the utility library

**Comment by rgagne** [comment]
Fixed in the next build
