### ISSUE TITLE
I want to change the activity value to Japanese 

### ISSUE THREAD

**Issue by hiroki-330** [weaveio/forum#65]
![Fluxweave および他 3 ページ - 職場 - Microsoft​ Edge 2021_03_06 12_24_46](https://user-images.githubusercontent.com/78060608/110193767-434a0880-7e79-11eb-8d92-ff3c96dfbaf9.png)

I wanted to change the "out" of the activity type display to Japanese, so I changed the value in the above photo to Japanese. 

![Fluxweave および他 3 ページ - 職場 - Microsoft​ Edge 2021_03_06 12_27_24](https://user-images.githubusercontent.com/78060608/110193774-4e9d3400-7e79-11eb-8dac-ec25f6fcd385.png)

![New Issue · weaveio_forum および他 4 ページ - 職場 - Microsoft​ Edge 2021_03_06 12_35_28](https://user-images.githubusercontent.com/78060608/110193785-5d83e680-7e79-11eb-996e-77960d9eadbb.png)

Then, even if I tapped suchedule in the above picture, nothing was selected for the activity type as shown in the picture below. 

![Fluxweave および他 3 ページ - 職場 - Microsoft​ Edge 2021_03_06 12_28_38](https://user-images.githubusercontent.com/78060608/110193790-6bd20280-7e79-11eb-8911-7b46137564e4.png)

When value is returned to English, it is restored. 
Should I change somewhere in the Layout of suchedule or the Layout of dashboard2? 
よろしくお願いします。

**Comment by rgagne** [comment]
Set display as to data and you should get what you are looking for
