### ISSUE TITLE
photo for tracker

### ISSUE THREAD

**Issue by shunyaogawa** [weaveio/forum#67]
![phototracker](https://user-images.githubusercontent.com/78076746/110286482-5e0eaf80-8028-11eb-916d-33ec969e9abe.png)
Is it possible to insert a photo such as a description in the tracker?

**Comment by Show-M** [comment]
確認です。
ユーザーへの説明用に使用する写真(アプリ管理側がアップロード)であり、ユーザー側が入力の一貫としてアップロードする写真ではないということで宜しいでしょうか？

**Comment by rgagne** [comment]
you can add a wiki page link; that will open a popup with the content

**Comment by shunyaogawa** [comment]
I think users don't upload photos.

I'll try using the Wiki.
If you don't know how, I will ask you another question.
