### ISSUE TITLE
Why doesn't body metric  get displayed on dispatch face?

### ISSUE THREAD

**Issue by Show-M** [weaveio/forum#69]
Data Query:
`given user[1aca4a8e-156d-4fdf-a127-bead09725f76], given tracker[cact]`
<img width="1398" alt="スクリーンショット 2021-03-09 22 25 36" src="https://user-images.githubusercontent.com/61481039/110477734-df4c6c00-8126-11eb-8289-5f7b5493e08c.png">
<img width="996" alt="スクリーンショット 2021-03-09 22 27 28" src="https://user-images.githubusercontent.com/61481039/110477739-dfe50280-8126-11eb-9dcc-198bff1609b3.png">

**Comment by rgagne** [comment]
if those are compute they won't be computed - that only happens when you open the dispatch because it is expensive; instead add the formula to the expression section per https://docs.fluxweave.com/Configuration/Trackers/

Right now it just supports one expression

**Comment by Show-M** [comment]
Not sure what you mean by "one  expression" 
Currently i have this in expression field, which is not working.
<img width="1171" alt="スクリーンショット 2021-03-17 9 41 07" src="https://user-images.githubusercontent.com/61481039/111397597-085f9480-8705-11eb-848a-d9aa521e7536.png">

**Comment by rgagne** [comment]
it was still wrong; I fixed it

The documentation:
https://docs.fluxweave.com/Configuration/Trackers/


You combined the expression and the template into one place (the expression)... but that isn't how it works.

**Comment by Show-M** [comment]
When there is null in metric, the expression get broken.

ex)
One of values is null
`
(values.CACT411Q1+values.CACT411Q2+values.CACT411Q3+values.CACT411Q4+values.CACT411Q5+values.CACT411Q6+values.CACT411Q7+values.CACTQ1 + values.CACTQ2 + values.CACTQ3 + values.CACTQ4 + values.CACTQ5)
`
