### ISSUE TITLE
Medicine Management Page  -Final Version

### ISSUE THREAD

**Issue by Show-M** [weaveio/forum#73]
Problem:
Users tend to forget detail of medicines they are taking.

Goal:
Make users remember details of medicines users take.

Method:
Let users add detail of their own medicine on weave app

Some note:
Orginal medicine data to be imported has medicine name + route of administration
**All the registered medicine data should be visible on 1 screen**
Precious Design by Woll is here: #58
Mapping: https://www.mindmeister.com/1811760967
Data Source: JAPAC 
<br>
<br>
Screen Design:
<img width="890" alt="スクリーンショット 2021-03-10 23 21 47" src="https://user-images.githubusercontent.com/61481039/110643533-88fb2e00-81f7-11eb-8ab5-f14541eea2ad.png">
<img width="885" alt="スクリーンショット 2021-03-10 23 21 53" src="https://user-images.githubusercontent.com/61481039/110643546-8d274b80-81f7-11eb-8771-f3dcedfca51e.png">
<img width="907" alt="スクリーンショット 2021-04-06 17 49 51" src="https://user-images.githubusercontent.com/61481039/113685123-e1dbba80-9700-11eb-9372-21b64fd7cb9f.png">
<img width="898" alt="スクリーンショット 2021-04-06 17 52 03" src="https://user-images.githubusercontent.com/61481039/113685159-e902c880-9700-11eb-90e4-079f6dedd175.png">
<img width="886" alt="スクリーンショット 2021-03-10 23 22 24" src="https://user-images.githubusercontent.com/61481039/110643559-8f89a580-81f7-11eb-9971-0d92b709a2d2.png">
<img width="875" alt="スクリーンショット 2021-03-10 23 22 32" src="https://user-images.githubusercontent.com/61481039/110643561-90223c00-81f7-11eb-8834-5af5540047e0.png">

**Comment by Show-M** [comment]
How data will be filled/provided
- Medicine product name:  xlm file
- Route of Administration: xlm file

how to filter only medicines related to asthma
 -  therapeutic category numbers:  Dr will indicate

**Comment by sarikabhimre18** [comment]
@Show-M can you please let me know about the access of mind map for more information also which is this screen ?

**Comment by Show-M** [comment]
@sarikabhimre18 
We will build this med page here. Anything here can be removed/modified.
<img width="1429" alt="スクリーンショット 2021-03-26 11 40 33" src="https://user-images.githubusercontent.com/61481039/112569861-4dcc4200-8e28-11eb-85dc-4484dd998ae7.png">


Everything except "Asthma attach" and "top", we need to build from scratch.
![Uploading スクリーンショット 2021-03-26 11.44.25.png…]()

**Comment by Show-M** [comment]
Where we need data on XLM. There are 3 data we need.
<img width="773" alt="スクリーンショット 2021-04-01 21 58 39" src="https://user-images.githubusercontent.com/61481039/113299001-5eece580-9337-11eb-92e6-667eed6678d3.png">
<brand.name en="販売名和名">ダイアップ坐剤6</brand.name>
We need only "ダイアップ坐剤6" part of data.

<img width="579" alt="スクリーンショット 2021-04-01 22 01 19" src="https://user-images.githubusercontent.com/61481039/113299027-644a3000-9337-11eb-9dcc-695826531cfa.png">
【剤形】
<br/>
／坐剤／外用
We need only "外用" part of data. If that is not possible, we can get simply "／坐剤／外用" part of data.
But First mean is better.

<img width="795" alt="スクリーンショット 2021-04-01 22 11 29" src="https://user-images.githubusercontent.com/61481039/113299032-64e2c680-9337-11eb-817f-3541043f1c5a.png">
<sccjno en="日本標準商品分類番号" label="日本標準商品分類番号">871139</sccjno>
We need only "871139" part of data.

**Comment by sarikabhimre18** [comment]
{
brand_name: "ダイアップ坐剤6",
Classification_Number: 871139,
external_user: "／坐剤／外用"
}

**Comment by Show-M** [comment]
Medicine name: "ダイアップ坐剤6",
Route of administration: "／坐剤／外用"
`Classification_Number: 871139` will NOT be in weave data. 
It will be used to sort out and remove some medicine from original data as not-every medicines in zip file will be used in the end.

処方日(Prescribled Date): select manually from calendar 
１日の服用回数(Nomber of dose in a day): select manually by scrolling
１回吸入回数(Number of inhalations per time) : select manually by scrolling

What are brand_name &  external_user ?

**Comment by sarikabhimre18** [comment]
@rgagne 
Here for the 処方日(Prescribled Date) there is which tracker metrics we used ?.Is their any metric for datepicker if yes then which is this ?

**Comment by Show-M** [comment]
@sarikabhimre18 
On json file you converted from xlm, we need following part of data.
e.g)-00000062.json
"brand.name": [
                                    {
                                        "_": "**クリノリル錠50**",
                                        "$": {
                                            "en": "販売名和名"
                                        }
                                    }
                                ],


"sccjno": [
                                    {
                                        "_": "**871149**",
                                        "$": {
                                            "en": "日本標準商品分類番号",
                                            "label": "日本標準商品分類番号"
                                        }
                                    }
                                ],

"srl.t": [
                                                            {
                                                                "dtl.t": [
                                                                    {
                                                                        "_": "【色】微赤色【剤形】**懸濁液剤／懸濁剤／外用**",
                                                                        "br": [
                                                                            "",
                                                                            "",
                                                                            ""
                                                                        ]
                                                                    }
                                                                ]
                                                            }
                                                        ]

**Comment by Show-M** [comment]
`”<sccjno en="日本標準商品分類番号" label="日本標準商品分類番号">873929</sccjno>“`
日本標準分類番号の８７に続く、３桁目からの３桁が薬効分類番号。

`定期薬と発作時服用薬は、どうやってデータから分類しますか？
`回答待ち。

`データをシステム内に入れる前に、先生方に「薬効分類表の３桁コード」を選択していただく必要があると思います。
`山本先生には確認しました220-229が、喘息関連と思う。

**Comment by sarikabhimre18** [comment]
@Show-M I didn't get this https://github.com/weaveio/forum/issues/73#issuecomment-813278383 is this for me ?

**Comment by Show-M** [comment]
no, it is just a note, plz ignore..

**Comment by Show-M** [comment]
@sarikabhimre18 
Can you extract only medicine data containing one of these numbers?
221,222,223,224,225,226,227,228,229
These will be the data we need for asthma project. Everything else we can cut off.

i.g)
Numbers we need to look at is 873929 in this case. 
87 is not important. "392" is where we need to check if it matches with 221-229 above. Last number, 9 is not important
`{"0":{"name":"ウロミテキサン注100mg","jsn":"873929","roa":"【色】無色澄明【剤形】／液剤／注射"}`

So, if the number was 822275, then we can see that it is asthma med as it contains "227"

**Comment by Show-M** [comment]
Things to be fixed: 
<img width="671" alt="スクリーンショット 2021-04-06 17 56 19" src="https://user-images.githubusercontent.com/61481039/113690511-74cb2380-9706-11eb-8013-023d8edfbc09.png">
<br>
<br>
<img width="605" alt="スクリーンショット 2021-04-06 17 56 42" src="https://user-images.githubusercontent.com/61481039/113690544-801e4f00-9706-11eb-988b-e51d3979a2f7.png">
To solve the 2nd issue, i think we need conditions such below:
```
If Route of med is A or B,  only 1 is displayed
if route of med is C, only 2 is displayed
```
<br>
<br>
After the submission, is it possible to display all the dispatch data on the HOME screen below?
This was the original idea... So, i would like to know if we can or can not due to generalization.
<img width="528" alt="スクリーンショット 2021-04-06 18 48 33" src="https://user-images.githubusercontent.com/61481039/113692712-c70d4400-9708-11eb-9e75-22794441ad31.png">

**Comment by sarikabhimre18** [comment]
@Show-M for #3 we can do that

**Comment by sarikabhimre18** [comment]
<srl.t>
<dtl.t>
【色】
<br/>
白色
<br/>
【剤形】
<br/>
素錠／錠剤／内用
<br/>
／／割線
</dtl.t>
</srl.t>

**Comment by sarikabhimre18** [comment]
![Screenshot_20210406_165646](https://user-images.githubusercontent.com/29194144/113704036-3f6c0900-96f9-11eb-94ab-6f32ae5464db.png)

**Comment by rgagne** [comment]
@sarikabhimre18 based on above the current xml to json conversion won't work. It is losing the line breaks. You'll need to find a different way

**Comment by Show-M** [comment]
Med page has been created though it needs final brush-up. 

I am closing this and opening a new one with all the confirmed data process etc.
