### ISSUE TITLE
Calendar display Language

### ISSUE THREAD

**Issue by hiroki-330** [weaveio/forum#74]
![Fluxweave および他 4 ページ - 職場 - Microsoft​ Edge 2021_03_11 17_31_21](https://user-images.githubusercontent.com/78060608/110758515-f35fad00-828f-11eb-957f-289f56a1f4ff.png)
![Fluxweave および他 4 ページ - 職場 - Microsoft​ Edge 2021_03_11 17_31_53](https://user-images.githubusercontent.com/78060608/110758562-feb2d880-828f-11eb-8f0e-9f923543090f.png)
![Fluxweave および他 4 ページ - 職場 - Microsoft​ Edge 2021_03_11 17_32_03](https://user-images.githubusercontent.com/78060608/110758586-05415000-8290-11eb-84d0-a98956b0d131.png)
I want to display the calendar in Japanese.
Please tell me where to change the metric etc.

**Comment by hiroki-330** [comment]
I don't want to change the activity value if possible .

**Comment by Show-M** [comment]
@rgagne 
I use web-weave in Japanese but, calendar display (Mon/Tue...Feb) are in English. 
Is that possible to change into Japanese? 

Mobile has Japanese version though.

**Comment by rgagne** [comment]
Both web and mobile display based on the users language setting.
