### ISSUE TITLE
Please tell me how to alarm function

### ISSUE THREAD

**Issue by hiroki-330** [weaveio/forum#75]
I would like to know how to set the alarm function.

お願いします。

**Comment by Show-M** [comment]
独立した機能で、ユーザー自身が全てを設定するアラームという事でよろしいでしょうか？

＊他のトラッカー等と連動しない

**Comment by hiroki-330** [comment]
ユーザー自身がすべてを設定するアラームで大丈夫です。
お願いします

**Comment by Show-M** [comment]
Am I missing anything?
<img width="1440" alt="スクリーンショット 2021-03-13 13 40 52" src="https://user-images.githubusercontent.com/61481039/111019352-fed2e580-8401-11eb-9c3d-2c5a37c8681b.png">
<img width="1434" alt="スクリーンショット 2021-03-13 13 41 03" src="https://user-images.githubusercontent.com/61481039/111019354-04303000-8402-11eb-9444-45f90f1027f9.png">
<img width="1437" alt="スクリーンショット 2021-03-13 13 41 20" src="https://user-images.githubusercontent.com/61481039/111019356-05f9f380-8402-11eb-9812-9b82b9c15818.png">

**Comment by hiroki-330** [comment]
曜日設定などはできるのですか？

**Comment by rgagne** [comment]
There are three parts:

1. User create / edit / remove user triggers; that's outlined above by adding a menu item
2. Triggers - these can be set by the user or created by the admin; if created by the admin the admin can set the day and time
3. Scripts that get called by the trigger

Scripts can do anything a user can do; there is a wide API available. Triggers can be set by the user (via the menu configuration) or via the admin.
