### ISSUE TITLE
Configure the script to actually send alarm reminders

### ISSUE THREAD

**Issue by rgagne** [weaveio/forum#81]
Current script doesn't do that

**Comment by rgagne** [comment]
Messages need some touch up

**Comment by rgagne** [comment]
I got my reminder; note that the reminders are in English so need to adjust

**Comment by Show-M** [comment]
I trired in different ways.
1. Create a new reminder and let the app stay on the page, then light turns off
2. Create a new reminder and move the app to background
3. create a new reminder and close the app

The reminder actually worked only on scenario 1. Can you have  a look again?

**Comment by rgagne** [comment]
The reminder should only work in 2 and 3... you don't get a push notification if the app is in the foreground.

Just tested it and received in scenarios 2 and 3. I can figure out a solution for 1 ... but it's somewhat of an edge case.
