### ISSUE TITLE
Plus button to create based on date context

### ISSUE THREAD

**Issue by rgagne** [weaveio/forum#82]
In calendar and other places; if the user selects a date then PLUS should create for that date rather than today.

**Comment by Show-M** [comment]
is this already on live for non-testflight app ?

**Comment by rgagne** [comment]
it is live on test flight

**Comment by Show-M** [comment]
I see. Dr uses only public build, not testflight version. Can we apply this change for public build too? 
Otherwise, we can ask them to join testflight.

**Comment by rgagne** [comment]
It takes 1-2 days to get builds approved - longer if we submit them over and over. We want to bundle changes together. Is there anything else urgent before we do a release?

**Comment by Show-M** [comment]
maybe...
https://github.com/weaveio/forum/issues/51
https://github.com/weaveio/woll/issues/244
https://github.com/weaveio/woll/issues/246

**Comment by Show-M** [comment]
done
