### ISSUE TITLE
"Espression" shows 0 if there is null value

### ISSUE THREAD

**Issue by Show-M** [weaveio/forum#84]
Depending on the age, 4-11 OR over-12, we use different metrics to be answered by patients.
Then we compute to get a score.

Now orange values get filled when patients are  over-12, otherwise they will be blanks. 
This blank-values are causing a problem. So that, compute there does not work....
<img width="1182" alt="スクリーンショット 2021-03-24 9 04 39" src="https://user-images.githubusercontent.com/61481039/112234890-da3c0080-8c80-11eb-8a8a-738d00b0c3b7.png">

**Comment by rgagne** [comment]
`ifNull` should work

`(ifNull(values.CACT411Q1)+...`

**Comment by Show-M** [comment]
umm....Can you have a look once again plz? 

example: `given dispatch[67d459ca-540a-4895-b6a2-5f2e5425f420]`
<img width="1415" alt="スクリーンショット 2021-03-24 19 48 39" src="https://user-images.githubusercontent.com/61481039/112298208-1e0f2400-8cda-11eb-8f39-db9ffc6bba38.png">

**Comment by rgagne** [comment]
fixed; there was an issue with ifNull.. template now supports simple math so just moved the expression into there

**Comment by Show-M** [comment]
I see the fixation on web. But same issue continues on iOS.
<img width="1437" alt="スクリーンショット 2021-04-25 18 20 57" src="https://user-images.githubusercontent.com/61481039/115988102-1c938d00-a5f3-11eb-8c1b-94b28af440b3.png">

**Comment by rgagne** [comment]
Because iOS has not been updated yet.
