### ISSUE TITLE
Medicine Screen management strategy

### ISSUE THREAD

**Issue by sarikabhimre18** [weaveio/forum#86]
@rgagne 
Create a Register Popup screen:-
-)Need to add new tracker metrics with checkbox and text field for input the medicine
-)Create a tracker for Register the medicine data with title and medicine fields
-)Show the Enter medicine details on the Popup(Will not sure about figure out how can be show the tracker info in Popup )

Create medicine search Screen:-
-)Create a screen from navigation to show the medicine details
-)Go through the code it look like create an [new search page for medicine] but not sure about configuration can you please let me know about it. 
-)When user click on the medicine from medicine search screen show the details Popup with register button

**Comment by rgagne** [comment]
Focus on the medicine search screen. Do the work in SmokeTestOrg rather than the woll app.

1. Add a new markup widget type <Markup__/> that can be included on a layout page
2. Data will be a JSON document under Content.. you can format as desired for now but we may change the shape
3. Focus on the UI interaction and flow

**Comment by sarikabhimre18** [comment]
@rgagne 
1) Created a markup widget at layout and create a json in content how can i connect the content and layout ?
2) Also their is when user click on medicine the another tracker form is open how can i connect the tracker to layout and how to customise the layout using tracker is their any reference example or i need to create an details screen component ?

**Comment by sarikabhimre18** [comment]
![scr1](https://user-images.githubusercontent.com/29194144/112987688-a0876000-9180-11eb-9102-97e807fe7b60.png)

**Comment by rgagne** [comment]
closing as obsolete
