### ISSUE TITLE
About marking 

### ISSUE THREAD

**Issue by keito-omura** [weaveio/forum#88]
![質問（詳細）](https://user-images.githubusercontent.com/78069712/112434257-b4991f00-8d86-11eb-9f7a-6ea7ec5f876f.png)
It is possible to mark a specific user, but is it a specification that the mark is removed when the page is moved?
How can I leave a mark even if I move the page?

**Comment by keito-omura** [comment]
Is there an answer to this question yet?

**Comment by rgagne** [comment]
The answer is that it's not supported.

**Comment by keito-omura** [comment]
I understood.
Thank you.
