### ISSUE TITLE
EDIT dispatch function on calendar 

### ISSUE THREAD

**Issue by Show-M** [weaveio/forum#95]
It looks like Doctor wants an ability to display all the dispatch-data + edit dispatch on this screen. 
![IMG_70C653E4B8FE-1](https://user-images.githubusercontent.com/61481039/112589682-e7095180-8e44-11eb-88f7-4da91ffaddd8.jpeg)

1. It does not make sense that users can only EDIT as there are chance where they need to DELETE. So it makes sense to add EDIT into Vertical ellipsis.

2. if 1 is ok, we need to set what items to display there.

3. But if we display all the dispatch-data on this screen ablove, what is the point of having this page, below...?
![IMG_D9E280AF7401-1](https://user-images.githubusercontent.com/61481039/112589834-22a41b80-8e45-11eb-9537-5f69804a8cdf.jpeg)

**Comment by rgagne** [comment]
partially complete; will display the entire dispatch (with the setting is configured); still need to click the dots to get the edit
