### ISSUE TITLE
Medicine management page (v2)

### ISSUE THREAD

**Issue by rgagne** [weaveio/forum#99]
# Goal

Provide a way to list, add via search against a document, dispatch backed lists. The initial goal is medicine management but the underlying components should support any type of list management.

Supporting documentation:
1. https://github.com/weaveio/forum/issues/73, https://github.com/weaveio/forum/issues/58, https://github.com/weaveio/forum/issues/86
1. [喘息アプリ(Asthma_App).pdf](https://github.com/weaveio/forum/files/6229184/Asthma_App.pdf)

Data:
1. There is a data document that contains an array of objects (in the initial case each object describes a medicine and provides information about how to administer, side effects, etc.).
2. Dispatches, one for each entry, are used to allow the user to create the list

The flow:
1. The list is populated via a dispatch query, e.g. `current user, given tracker [medicine-entry]`
2. The add button allows the user to search the data document configured and select an entry; using that entry and additional information added a dispatch is created

# Requirements

## User flow

- [x] 1. Default view will be a list block populated by the dispatch query; an Add action will be available

- [x] 2. User will click add to begin the search flow; this will match a data object, allow the user to edit it and save as a dispatch and then return to the list block

- [x] 3. The list block will display matches based on dispatch query; it will use ParseTemplate for a series of display lines matched against the dispatch

- [x] 4. Clicking a line will open the dispatch using DispatchInteractive

- [x] 5. User can edit / remove lines; this will open the dispatch for editing or delete the dispatch

## Configuration

The functionality will be configuration driven. There will be two elements: Data search functionality and the Saved attributes functionality. A user will search for a medicine using "data search". Once finding a medicine they will use "saved attributes" to configure the record and save it (it will get saved as a dispatch).

## Data search functionality

The data will be stored in JSON format as a document with data elements stored in the JSON object as an array of objects. This can be loaded using the LayoutHOC component. The data search configuration should have a path, the attribute to match against and filters so ignore objects that don't match the criteria. Regex or ParseConditional can be used for the filters.

The user will type into an edit field and match against the data.

## Saved attributes

Once the user selects an object based on search they will be presented with a form that includes data from the object (configured) and additional entry components using the $capture.as notation (used by trackers). The user will complete the form and save. This entire data (attributes from matched object + additional entry fields) will be saved as a dispatch. The tracker to use for saving will be configured.

## List block

Each list block will contain.

1. A dispatch query (for populating the list)
2. A series of lines using ParseTemplate for displaying the title and subheader lines for each list item using the dispatch
3. The ability to add / edit / remove a dispatch
4. Clicking the entry will open the dispatch

## Architecture

Use the Layout widget capability within the platform. The widget should display a list block. It should be possible to have more than one list block in a view. The data will be stored as Content and loaded via LayoutHOC. Keep components small and self contained (no longer than 200-300 lines each) breaking down into smaller components complex logic. Use utility classes where appropriate.

Note that "medicine" can be any data element. The majority of the functionality should be driven by the configuration.

**Comment by sarikabhimre18** [comment]
![step1](https://user-images.githubusercontent.com/29194144/113250326-ea398d00-92dd-11eb-8a92-16de16bd9b5a.png)

**Comment by sarikabhimre18** [comment]
`{
  "Data": [
    {
      "values": {
        "medicineName": "test medicine",
        "routeName": "test route name",
        "noOfDose": "3",
        "date": ""
      },
      "_id": "33"
    },
    {
      "values": {
        "medicineName": "test 2 medicine",
        "routeName": "test2 route name",
        "noOfDose": "3",
        "date": ""
      },
      "_id": "34"
    },
    {
      "values": {
        "medicineName": "test 3 medicine",
        "routeName": "test3 route name",
        "noOfDose": "3",
        "date": ""
      },
      "_id": "35"
    }
  ]
}`

**Comment by Show-M** [comment]
@sarikabhimre18 
If this ticket has been resolved, can you close it?

**Comment by Show-M** [comment]
@sarikabhimre18 
Plz close this ticket if it is done.
